### ISSUE TITLE
How do you make scripts by default exicutible ?

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/flux#10]

**Comment by strasharo** [comment]
Everything necessary is already executable in the current repo:

root@kalif:~/flux# ls -l flux Installer.sh kali/fluxion kali/airmon 
-rwxr-xr-x 1 root root 260758 Mar  6 20:51 flux
-rwxr-xr-x 1 root root   5112 Mar  6 20:51 Installer.sh
-rwxr-xr-x 1 root root  35379 Mar  6 20:51 kali/airmon
-rwxr-xr-x 1 root root 260712 Mar  6 20:51 kali/fluxion
root@kalif:~/flux# 

What do you mean?

**Comment by deltaxflux** [comment]
I mean how to make files executible in github (because i´m a github noob)

**Comment by strasharo** [comment]
What software are you using to commit here?
In case you're using the github web interface, I'm not quite sure if there is way to do it from there.
I'm using git from the command line and after chmod-ing the file as executable the change is detected by git and it can be committed afterwards. For example:

[strshr@T14 flux] $ ls -l README.md 
-rw-rw-r-- 1 strshr strshr 1680 Mar  6 22:15 README.md
[strshr@T14 flux] $ chmod +x README.md 
[strshr@T14 flux] $ git diff
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
[strshr@T14 flux] $ git add README.md 
[strshr@T14 flux] $ git commit -m "mode change for demo purposes https://github.com/deltaxflux/flux/issues/10"
[master d050fa7] mode change for demo purposes https://github.com/deltaxflux/flux/issues/10
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 README.md
[strshr@T14 flux] $ git push origin master
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 268 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To git@github.com:deltaxflux/flux.git
   5f0b350..d050fa7  master -> master
[strshr@T14 flux] $ chmod -x README.md 
[strshr@T14 flux] $ git add README.md 
[strshr@T14 flux] $ git commit -m "revert mode change for demo purposes https://github.com/deltaxflux/flux/issues/10"
[master b406d27] revert mode change for demo purposes https://github.com/deltaxflux/flux/issues/10
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100755 => 100644 README.md
[strshr@T14 flux] $ git push origin master
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 273 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To git@github.com:deltaxflux/flux.git
   d050fa7..b406d27  master -> master
[strshr@T14 flux] $
