### ISSUE TITLE
flux is trying to restart an unexisting service

### ISSUE THREAD

**Issue by strasharo** [deltaxflux/flux#3]
https://github.com/deltaxflux/flux/blob/master/flux#L170

It's trying to restart a service called networkmanager, while the proper name of the service on kali/debian is network-manager:
```
root@kalif:~# ls -la /etc/init.d | grep -i manager
-rwxr-xr-x   1 root root 1757 Dec 24 01:57 network-manager
root@kalif:~# 

```

**Comment by deltaxflux** [comment]
Thank you for sharing, i fixed it now. If you have more bugs please share :100:

**Comment by strasharo** [comment]
This commit just reversed the fix for fluxion:
https://github.com/deltaxflux/flux/commit/5b475e5f9de277795a2cb86760c9ee0c9eb7cc74#diff-f93830bf425129bfdcf461784a85367bL174
