### ISSUE TITLE
Flux is unable to parse the output of the latest airmon-ng

### ISSUE THREAD

**Issue by strasharo** [deltaxflux/flux#4]
The issue is here:
https://github.com/deltaxflux/flux/blob/master/flux#L614

Current airmon-ng produces output like this:
root@kalif:~# airmon-ng

PHY Interface Driver Chipset

phy0 alfa1 rtl8187 Realtek Semiconductor Corp. RTL8187
phy1 alfa2 ath9k_htc Atheros Communications, Inc. AR9271 802.11n

root@kalif:~#

Where lines containing adapters don't contain a dash (-) as your script expects.

Your script is relying on output like this:
root@kalif:~# ./airmon

Interface Chipset Driver

alfa1 Realtek RTL8187L rtl8187 - [phy0]
alfa2 Atheros AR9271 ath9k - [phy1]

root@kalif:~#

Where you have a dash on every line with adapter. 
Such output is provided by the following script:
https://github.com/kernel-64/linset/blob/81e637542b2cd62a6ea6c307183b7488bf8fd277/airmon

There are two options to fix this issue. You can either:
1) Ship a separate airmon script with flux and execute it instead of the OS built-in airmon-ng.
2) Modify the parsing logic of your script to work with the current versions of airmon-ng.

Let me know if you need any assistance with that.

Thank you.

**Comment by deltaxflux** [comment]
There is a kali patch, look at the kali folder and download fluxion. It is for the latest version aircrack-ng version where mon0 to wlan0 changed. Fluxion does work on Kali 2 and Kali 2 2016 (latest), already tested 
Thank you for your support

**Comment by strasharo** [comment]
Thanks, didn't notice it earlier. :) It works.
