### ISSUE TITLE
Flux : problem install

### ISSUE THREAD

**Issue by cetrobo** [deltaxflux/flux#7]
Hi , i get error bash sudo ./flux: No such file or folder like this

**Comment by deltaxflux** [comment]
yes because you don´t use
sudo chmod +x flux 
it allow to execute the program

**Comment by strasharo** [comment]
All of the files are already executable by default when checked in from the repository and sudo is not mandatory for chmod if the user is able to write to that directory. Is flux located in the directory you're currently in?

**Comment by deltaxflux** [comment]
oh yeah maby he is in the wrong directory

**Comment by fouad3122** [comment]
hi ، i need some help about how install script fluxion in wifislax 
cd Desktop 
ls 
cd flux-master
ls
??????? thanks..................

**Comment by strasharo** [comment]
In order to use flux, the user must have basic knowledge regarding the Linux operating system. This is the place to report bugs in flux/fluxion and not a general help forum.
