### ISSUE TITLE
Getting error trying to run flux

### ISSUE THREAD

**Issue by trivera90** [deltaxflux/flux#8]
All files are executable and i am on root user.
This happens when i try to run flux

root@TimsMini:~/Desktop/flux-master# ./flux

./flux: line 98: syntax error near unexpected token `sudo'
./flux: line 98: `	sudo chmod +x Installer.sh '

happens even if i use sudo which i really dont need to since i am root user

**Comment by strasharo** [comment]
Can you try running fluxion from the kali subdirectory instead, please?

**Comment by trivera90** [comment]
ah! i Didnt notice that there. Program runs now thanks ! now to test it out :)

**Comment by strasharo** [comment]
Cheers. fluxion is being currently actively developed, the other one will be eventually deprecated. :)

**Comment by strasharo** [comment]
I see that @deltaxflux already took care of this one:
https://github.com/deltaxflux/flux/commit/af509d85968e966bdffa94cd609318388808dc8b
